### ISSUE TITLE
Unknown configuration profile: 'singularity'

### ISSUE THREAD

**Issue by Vikash84** [hawaiidatascience/metaflowmics#5]
nextflow run Pipeline-16S -profile singularity --reads "data/*_R{1,2}_001.fastq.gz" --referenceAln databases/silva/v138/silva.nr_v138.align --referenceTax databases/silva/v138/silva.nr_v138.tax 

N E X T F L O W  ~  version 20.04.1
Launching `Pipeline-16S/main.nf` [determined_ekeblad] - revision: d665331f9a
Unknown configuration profile: 'singularity'

**Comment by Puumanamana** [comment]
Sorry I didn't see this issue before. There is no profile named singularity in the current version of the pipeline. You can choose "local" if you are running the pipeline locally, or create your own if you're running on a hpc or a cloud computing service.
